# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 7097b6d9-43ea-533c-9025-5c8bb8c671f2

on:
  push:
    branches:
      - krkothari/test-deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fruoccopublic.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c0c556e10c6c4677a7303603032c00f9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8cef9ab6e8a54fbb86231cf5c36c3d65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fruoccopublic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c0c556e10c6c4677a7303603032c00f9 }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '7097b6d9-43ea-533c-9025-5c8bb8c671f2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_057c243354804bb3bc65b5b403df5267 }}
        images: 'fruoccopublic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c0c556e10c6c4677a7303603032c00f9 }}/sample-app-aoai-chatgpt:${{ github.sha }}'